---
- name: install forgejo packages
  with_items: "{{ forgejo_packages }}"
  pkgng:
    name: "{{ item.name }}"
    state: latest
  notify:
    - restart forgejo

- name: configure forgejo
  template:
    src: app.ini.j2
    dest: /usr/local/etc/forgejo/conf/app.ini
    owner: root
    group: git
    mode: 0660
  notify:
    - restart forgejo

- name: enable forgejo
  template:
    src: forgejo.j2
    dest: /etc/rc.conf.d/forgejo
  notify:
    - restart forgejo
